inherit_from: .rubocop_todo.yml

Style/AsciiIdentifiers:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'

Style/AsciiComments:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'

Style/RaiseArgs:
  Exclude:
    - 'lib/**/*'

Style/SpecialGlobalVars:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
